apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: QA Test
on:
  push:
    branches:
      - main
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: QA-env
          artifact-id: 575c9071-06aa-49c7-9e58-6700b60ed683
          target-environment: QA